INSERT INTO codes (country_code, polish_title) VALUES ('AFG', 'Afganistan');
INSERT INTO codes (country_code, polish_title) VALUES ('ALB', 'Albania');
INSERT INTO codes (country_code, polish_title) VALUES ('DZA', 'Algieria');
INSERT INTO codes (country_code, polish_title) VALUES ('AND', 'Andora');
INSERT INTO codes (country_code, polish_title) VALUES ('AGO', 'Angola');
INSERT INTO codes (country_code, polish_title) VALUES ('AIA', 'Anguilla');
INSERT INTO codes (country_code, polish_title) VALUES ('ATA', 'Antarktyka');
INSERT INTO codes (country_code, polish_title) VALUES ('ATG', 'Antigua i Barbuda');
INSERT INTO codes (country_code, polish_title) VALUES ('SAU', 'Arabia Saudyjska');
INSERT INTO codes (country_code, polish_title) VALUES ('ARG', 'Argentyna');
INSERT INTO codes (country_code, polish_title) VALUES ('ARM', 'Armenia');
INSERT INTO codes (country_code, polish_title) VALUES ('ABW', 'Aruba');
INSERT INTO codes (country_code, polish_title) VALUES ('AUS', 'Australia');
INSERT INTO codes (country_code, polish_title) VALUES ('AUT', 'Austria');
INSERT INTO codes (country_code, polish_title) VALUES ('AZE', 'Azerbejdżan');
INSERT INTO codes (country_code, polish_title) VALUES ('BHS', 'Bahamy');
INSERT INTO codes (country_code, polish_title) VALUES ('BHR', 'Bahrajn');
INSERT INTO codes (country_code, polish_title) VALUES ('BGD', 'Bangladesz');
INSERT INTO codes (country_code, polish_title) VALUES ('BRB', 'Barbados');
INSERT INTO codes (country_code, polish_title) VALUES ('BEL', 'Belgia');
INSERT INTO codes (country_code, polish_title) VALUES ('BLZ', 'Belize');
INSERT INTO codes (country_code, polish_title) VALUES ('BEN', 'Benin');
INSERT INTO codes (country_code, polish_title) VALUES ('BMU', 'Bermudy');
INSERT INTO codes (country_code, polish_title) VALUES ('BTN', 'Bhutan');
INSERT INTO codes (country_code, polish_title) VALUES ('BLR', 'Białoruś');
INSERT INTO codes (country_code, polish_title) VALUES ('BOL', 'Boliwia');
INSERT INTO codes (country_code, polish_title) VALUES ('BES', 'Bonaire, Sint Eustatius i Saba');
INSERT INTO codes (country_code, polish_title) VALUES ('BIH', 'Bośnia i Hercegowina');
INSERT INTO codes (country_code, polish_title) VALUES ('BWA', 'Botswana');
INSERT INTO codes (country_code, polish_title) VALUES ('BRA', 'Brazylia');
INSERT INTO codes (country_code, polish_title) VALUES ('BRN', 'Brunei');
INSERT INTO codes (country_code, polish_title) VALUES ('IOT', 'Brytyjskie Terytorium Oceanu Indyjskiego');
INSERT INTO codes (country_code, polish_title) VALUES ('VGB', 'Brytyjskie Wyspy Dziewicze');
INSERT INTO codes (country_code, polish_title) VALUES ('BGR', 'Bułgaria');
INSERT INTO codes (country_code, polish_title) VALUES ('BFA', 'Burkina Faso');
INSERT INTO codes (country_code, polish_title) VALUES ('BDI', 'Burundi');
INSERT INTO codes (country_code, polish_title) VALUES ('CHL', 'Chile');
INSERT INTO codes (country_code, polish_title) VALUES ('CHN', 'Chiny');
INSERT INTO codes (country_code, polish_title) VALUES ('HRV', 'Chorwacja');
INSERT INTO codes (country_code, polish_title) VALUES ('CUW', 'Curaçao');
INSERT INTO codes (country_code, polish_title) VALUES ('CYP', 'Cypr');
INSERT INTO codes (country_code, polish_title) VALUES ('TCD', 'Czad');
INSERT INTO codes (country_code, polish_title) VALUES ('MNE', 'Czarnogóra');
INSERT INTO codes (country_code, polish_title) VALUES ('CZE', 'Czechy');
INSERT INTO codes (country_code, polish_title) VALUES ('UMI', 'Dalekie Wyspy Mniejsze Stanów Zjednoczonych');
INSERT INTO codes (country_code, polish_title) VALUES ('DNK', 'Dania');
INSERT INTO codes (country_code, polish_title) VALUES ('COD', 'Demokratyczna Republika Konga');
INSERT INTO codes (country_code, polish_title) VALUES ('DMA', 'Dominika');
INSERT INTO codes (country_code, polish_title) VALUES ('DOM', 'Dominikana');
INSERT INTO codes (country_code, polish_title) VALUES ('DJI', 'Dżibuti');
INSERT INTO codes (country_code, polish_title) VALUES ('EGY', 'Egipt');
INSERT INTO codes (country_code, polish_title) VALUES ('ECU', 'Ekwador');
INSERT INTO codes (country_code, polish_title) VALUES ('ERI', 'Erytrea');
INSERT INTO codes (country_code, polish_title) VALUES ('EST', 'Estonia');
INSERT INTO codes (country_code, polish_title) VALUES ('ETH', 'Etiopia');
INSERT INTO codes (country_code, polish_title) VALUES ('FLK', 'Falklandy');
INSERT INTO codes (country_code, polish_title) VALUES ('FJI', 'Fidżi');
INSERT INTO codes (country_code, polish_title) VALUES ('PHL', 'Filipiny');
INSERT INTO codes (country_code, polish_title) VALUES ('FIN', 'Finlandia');
INSERT INTO codes (country_code, polish_title) VALUES ('FRA', 'Francja');
INSERT INTO codes (country_code, polish_title) VALUES ('ATF', 'Francuskie Terytoria Południowe i Antarktyczne');
INSERT INTO codes (country_code, polish_title) VALUES ('GAB', 'Gabon');
INSERT INTO codes (country_code, polish_title) VALUES ('GMB', 'Gambia');
INSERT INTO codes (country_code, polish_title) VALUES ('SGS', 'Georgia Południowa i Sandwich Południowy');
INSERT INTO codes (country_code, polish_title) VALUES ('GHA', 'Ghana');
INSERT INTO codes (country_code, polish_title) VALUES ('GIB', 'Gibraltar');
INSERT INTO codes (country_code, polish_title) VALUES ('GRC', 'Grecja');
INSERT INTO codes (country_code, polish_title) VALUES ('GRD', 'Grenada');
INSERT INTO codes (country_code, polish_title) VALUES ('GRL', 'Grenlandia');
INSERT INTO codes (country_code, polish_title) VALUES ('GEO', 'Gruzja');
INSERT INTO codes (country_code, polish_title) VALUES ('GUM', 'Guam');
INSERT INTO codes (country_code, polish_title) VALUES ('GGY', 'Guernsey');
INSERT INTO codes (country_code, polish_title) VALUES ('GUF', 'Gujana Francuska');
INSERT INTO codes (country_code, polish_title) VALUES ('GUY', 'Gujana');
INSERT INTO codes (country_code, polish_title) VALUES ('GLP', 'Gwadelupa');
INSERT INTO codes (country_code, polish_title) VALUES ('GTM', 'Gwatemala');
INSERT INTO codes (country_code, polish_title) VALUES ('GNB', 'Gwinea Bissau');
INSERT INTO codes (country_code, polish_title) VALUES ('GNQ', 'Gwinea Równikowa');
INSERT INTO codes (country_code, polish_title) VALUES ('GIN', 'Gwinea');
INSERT INTO codes (country_code, polish_title) VALUES ('HTI', 'Haiti');
INSERT INTO codes (country_code, polish_title) VALUES ('ESP', 'Hiszpania');
INSERT INTO codes (country_code, polish_title) VALUES ('NLD', 'Holandia');
INSERT INTO codes (country_code, polish_title) VALUES ('HND', 'Honduras');
INSERT INTO codes (country_code, polish_title) VALUES ('HKG', 'Hongkong');
INSERT INTO codes (country_code, polish_title) VALUES ('IND', 'Indie');
INSERT INTO codes (country_code, polish_title) VALUES ('IDN', 'Indonezja');
INSERT INTO codes (country_code, polish_title) VALUES ('IRQ', 'Irak');
INSERT INTO codes (country_code, polish_title) VALUES ('IRN', 'Iran');
INSERT INTO codes (country_code, polish_title) VALUES ('IRL', 'Irlandia');
INSERT INTO codes (country_code, polish_title) VALUES ('ISL', 'Islandia');
INSERT INTO codes (country_code, polish_title) VALUES ('ISR', 'Izrael');
INSERT INTO codes (country_code, polish_title) VALUES ('JAM', 'Jamajka');
INSERT INTO codes (country_code, polish_title) VALUES ('JPN', 'Japonia');
INSERT INTO codes (country_code, polish_title) VALUES ('YEM', 'Jemen');
INSERT INTO codes (country_code, polish_title) VALUES ('JEY', 'Jersey');
INSERT INTO codes (country_code, polish_title) VALUES ('JOR', 'Jordania');
INSERT INTO codes (country_code, polish_title) VALUES ('CYM', 'Kajmany');
INSERT INTO codes (country_code, polish_title) VALUES ('KHM', 'Kambodża');
INSERT INTO codes (country_code, polish_title) VALUES ('CMR', 'Kamerun');
INSERT INTO codes (country_code, polish_title) VALUES ('CAN', 'Kanada');
INSERT INTO codes (country_code, polish_title) VALUES ('QAT', 'Katar');
INSERT INTO codes (country_code, polish_title) VALUES ('KAZ', 'Kazachstan');
INSERT INTO codes (country_code, polish_title) VALUES ('KEN', 'Kenia');
INSERT INTO codes (country_code, polish_title) VALUES ('KGZ', 'Kirgistan');
INSERT INTO codes (country_code, polish_title) VALUES ('KIR', 'Kiribati');
INSERT INTO codes (country_code, polish_title) VALUES ('COL', 'Kolumbia');
INSERT INTO codes (country_code, polish_title) VALUES ('COM', 'Komory');
INSERT INTO codes (country_code, polish_title) VALUES ('COG', 'Kongo');
INSERT INTO codes (country_code, polish_title) VALUES ('KOR', 'Korea Południowa');
INSERT INTO codes (country_code, polish_title) VALUES ('PRK', 'Korea Północna');
INSERT INTO codes (country_code, polish_title) VALUES ('CRI', 'Kostaryka');
INSERT INTO codes (country_code, polish_title) VALUES ('CUB', 'Kuba');
INSERT INTO codes (country_code, polish_title) VALUES ('KWT', 'Kuwejt');
INSERT INTO codes (country_code, polish_title) VALUES ('LAO', 'Laos');
INSERT INTO codes (country_code, polish_title) VALUES ('LSO', 'Lesotho');
INSERT INTO codes (country_code, polish_title) VALUES ('LBN', 'Liban');
INSERT INTO codes (country_code, polish_title) VALUES ('LBR', 'Liberia');
INSERT INTO codes (country_code, polish_title) VALUES ('LBY', 'Libia');
INSERT INTO codes (country_code, polish_title) VALUES ('LIE', 'Liechtenstein');
INSERT INTO codes (country_code, polish_title) VALUES ('LTU', 'Litwa');
INSERT INTO codes (country_code, polish_title) VALUES ('LUX', 'Luksemburg');
INSERT INTO codes (country_code, polish_title) VALUES ('LVA', 'Łotwa');
INSERT INTO codes (country_code, polish_title) VALUES ('MKD', 'Macedonia');
INSERT INTO codes (country_code, polish_title) VALUES ('MDG', 'Madagaskar');
INSERT INTO codes (country_code, polish_title) VALUES ('MYT', 'Majotta');
INSERT INTO codes (country_code, polish_title) VALUES ('MAC', 'Makau');
INSERT INTO codes (country_code, polish_title) VALUES ('MWI', 'Malawi');
INSERT INTO codes (country_code, polish_title) VALUES ('MDV', 'Malediwy');
INSERT INTO codes (country_code, polish_title) VALUES ('MYS', 'Malezja');
INSERT INTO codes (country_code, polish_title) VALUES ('MLI', 'Mali');
INSERT INTO codes (country_code, polish_title) VALUES ('MLT', 'Malta');
INSERT INTO codes (country_code, polish_title) VALUES ('MNP', 'Mariany Północne');
INSERT INTO codes (country_code, polish_title) VALUES ('MAR', 'Maroko');
INSERT INTO codes (country_code, polish_title) VALUES ('MTQ', 'Martynika');
INSERT INTO codes (country_code, polish_title) VALUES ('MRT', 'Mauretania');
INSERT INTO codes (country_code, polish_title) VALUES ('MUS', 'Mauritius');
INSERT INTO codes (country_code, polish_title) VALUES ('MEX', 'Meksyk');
INSERT INTO codes (country_code, polish_title) VALUES ('FSM', 'Mikronezja');
INSERT INTO codes (country_code, polish_title) VALUES ('MMR', 'Mjanma');
INSERT INTO codes (country_code, polish_title) VALUES ('MDA', 'Mołdawia');
INSERT INTO codes (country_code, polish_title) VALUES ('MCO', 'Monako');
INSERT INTO codes (country_code, polish_title) VALUES ('MNG', 'Mongolia');
INSERT INTO codes (country_code, polish_title) VALUES ('MSR', 'Montserrat');
INSERT INTO codes (country_code, polish_title) VALUES ('MOZ', 'Mozambik');
INSERT INTO codes (country_code, polish_title) VALUES ('NAM', 'Namibia');
INSERT INTO codes (country_code, polish_title) VALUES ('NRU', 'Nauru');
INSERT INTO codes (country_code, polish_title) VALUES ('NPL', 'Nepal');
INSERT INTO codes (country_code, polish_title) VALUES ('DEU', 'Niemcy');
INSERT INTO codes (country_code, polish_title) VALUES ('NER', 'Niger');
INSERT INTO codes (country_code, polish_title) VALUES ('NGA', 'Nigeria');
INSERT INTO codes (country_code, polish_title) VALUES ('NIC', 'Nikaragua');
INSERT INTO codes (country_code, polish_title) VALUES ('NIU', 'Niue');
INSERT INTO codes (country_code, polish_title) VALUES ('NFK', 'Norfolk');
INSERT INTO codes (country_code, polish_title) VALUES ('NOR', 'Norwegia');
INSERT INTO codes (country_code, polish_title) VALUES ('NCL', 'Nowa Kaledonia');
INSERT INTO codes (country_code, polish_title) VALUES ('NZL', 'Nowa Zelandia');
INSERT INTO codes (country_code, polish_title) VALUES ('OMN', 'Oman');
INSERT INTO codes (country_code, polish_title) VALUES ('PAK', 'Pakistan');
INSERT INTO codes (country_code, polish_title) VALUES ('PLW', 'Palau');
INSERT INTO codes (country_code, polish_title) VALUES ('PSE', 'Palestyna');
INSERT INTO codes (country_code, polish_title) VALUES ('PAN', 'Panama');
INSERT INTO codes (country_code, polish_title) VALUES ('PNG', 'Papua-Nowa Gwinea');
INSERT INTO codes (country_code, polish_title) VALUES ('PRY', 'Paragwaj');
INSERT INTO codes (country_code, polish_title) VALUES ('PER', 'Peru');
INSERT INTO codes (country_code, polish_title) VALUES ('PCN', 'Pitcairn');
INSERT INTO codes (country_code, polish_title) VALUES ('PYF', 'Polinezja Francuska');
INSERT INTO codes (country_code, polish_title) VALUES ('POL', 'Polska');
INSERT INTO codes (country_code, polish_title) VALUES ('PRI', 'Portoryko');
INSERT INTO codes (country_code, polish_title) VALUES ('PRT', 'Portugalia');
INSERT INTO codes (country_code, polish_title) VALUES ('ZAF', 'Południowa Afryka');
INSERT INTO codes (country_code, polish_title) VALUES ('CAF', 'Republika Środkowoafrykańska');
INSERT INTO codes (country_code, polish_title) VALUES ('CPV', 'Republika Zielonego Przylądka');
INSERT INTO codes (country_code, polish_title) VALUES ('REU', 'Reunion');
INSERT INTO codes (country_code, polish_title) VALUES ('RUS', 'Rosja');
INSERT INTO codes (country_code, polish_title) VALUES ('ROU', 'Rumunia');
INSERT INTO codes (country_code, polish_title) VALUES ('RWA', 'Rwanda');
INSERT INTO codes (country_code, polish_title) VALUES ('ESH', 'Sahara Zachodnia');
INSERT INTO codes (country_code, polish_title) VALUES ('KNA', 'Saint Kitts i Nevis');
INSERT INTO codes (country_code, polish_title) VALUES ('LCA', 'Saint Lucia');
INSERT INTO codes (country_code, polish_title) VALUES ('VCT', 'Saint Vincent i Grenadyny');
INSERT INTO codes (country_code, polish_title) VALUES ('BLM', 'Saint-Barthélemy');
INSERT INTO codes (country_code, polish_title) VALUES ('MAF', 'Saint-Martin');
INSERT INTO codes (country_code, polish_title) VALUES ('SPM', 'Saint-Pierre i Miquelon');
INSERT INTO codes (country_code, polish_title) VALUES ('SLV', 'Salwador');
INSERT INTO codes (country_code, polish_title) VALUES ('ASM', 'Samoa Amerykańskie');
INSERT INTO codes (country_code, polish_title) VALUES ('WSM', 'Samoa');
INSERT INTO codes (country_code, polish_title) VALUES ('SMR', 'San Marino');
INSERT INTO codes (country_code, polish_title) VALUES ('SEN', 'Senegal');
INSERT INTO codes (country_code, polish_title) VALUES ('SRB', 'Serbia');
INSERT INTO codes (country_code, polish_title) VALUES ('SYC', 'Seszele');
INSERT INTO codes (country_code, polish_title) VALUES ('SLE', 'Sierra Leone');
INSERT INTO codes (country_code, polish_title) VALUES ('SGP', 'Singapur');
INSERT INTO codes (country_code, polish_title) VALUES ('SXM', 'Sint Maarten');
INSERT INTO codes (country_code, polish_title) VALUES ('SVK', 'Słowacja');
INSERT INTO codes (country_code, polish_title) VALUES ('SVN', 'Słowenia');
INSERT INTO codes (country_code, polish_title) VALUES ('SOM', 'Somalia');
INSERT INTO codes (country_code, polish_title) VALUES ('LKA', 'Sri Lanka');
INSERT INTO codes (country_code, polish_title) VALUES ('USA', 'Stany Zjednoczone');
INSERT INTO codes (country_code, polish_title) VALUES ('SWZ', 'Eswatini');
INSERT INTO codes (country_code, polish_title) VALUES ('SDN', 'Sudan');
INSERT INTO codes (country_code, polish_title) VALUES ('SSD', 'Sudan Południowy');
INSERT INTO codes (country_code, polish_title) VALUES ('SUR', 'Surinam');
INSERT INTO codes (country_code, polish_title) VALUES ('SJM', 'Svalbard i Jan Mayen');
INSERT INTO codes (country_code, polish_title) VALUES ('SYR', 'Syria');
INSERT INTO codes (country_code, polish_title) VALUES ('CHE', 'Szwajcaria');
INSERT INTO codes (country_code, polish_title) VALUES ('SWE', 'Szwecja');
INSERT INTO codes (country_code, polish_title) VALUES ('TJK', 'Tadżykistan');
INSERT INTO codes (country_code, polish_title) VALUES ('THA', 'Tajlandia');
INSERT INTO codes (country_code, polish_title) VALUES ('TWN', 'Tajwan');
INSERT INTO codes (country_code, polish_title) VALUES ('TZA', 'Tanzania');
INSERT INTO codes (country_code, polish_title) VALUES ('TLS', 'Timor Wschodni');
INSERT INTO codes (country_code, polish_title) VALUES ('TGO', 'Togo');
INSERT INTO codes (country_code, polish_title) VALUES ('TKL', 'Tokelau');
INSERT INTO codes (country_code, polish_title) VALUES ('TON', 'Tonga');
INSERT INTO codes (country_code, polish_title) VALUES ('TTO', 'Trynidad i Tobago');
